import React, { useState } from 'react';
import { Sparkles, Network, Star, GitCommit, Layers, Play } from 'lucide-react';

export default function RecommendationList({
  recommendations,
  selectedUser,
  algoMode,
  setAlgoMode,
  onSelectMovie,
  onHighlightPath
}) {
  const [hoveredPath, setHoveredPath] = useState(null);

  return (
    <div className="space-y-6">
      
      {/* Header & Algorithm Switcher Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 glass-panel p-5 rounded-2xl border border-slate-800">
        <div>
          <h2 className="text-xl font-extrabold text-white flex items-center space-x-2">
            <Sparkles className="w-5 h-5 text-indigo-400" />
            <span>Graph Recommendations for {selectedUser.name}</span>
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Personalized recommendations generated by graph path traversal & PageRank walks
          </p>
        </div>

        {/* Algorithm Modes */}
        <div className="flex items-center space-x-1 bg-slate-900/90 p-1 rounded-xl border border-slate-800 self-start sm:self-auto text-xs">
          <button
            onClick={() => setAlgoMode('hybrid')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
              algoMode === 'hybrid'
                ? 'bg-indigo-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Hybrid Graph
          </button>
          <button
            onClick={() => setAlgoMode('collaborative')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
              algoMode === 'collaborative'
                ? 'bg-amber-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Collaborative Paths
          </button>
          <button
            onClick={() => setAlgoMode('content')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
              algoMode === 'content'
                ? 'bg-cyan-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Content Entity
          </button>
          <button
            onClick={() => setAlgoMode('pagerank')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
              algoMode === 'pagerank'
                ? 'bg-rose-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            PageRank Walk
          </button>
        </div>
      </div>

      {/* Movie Recommendations Grid */}
      {recommendations.length === 0 ? (
        <div className="glass-panel p-12 rounded-2xl border border-slate-800 text-center space-y-3">
          <Network className="w-12 h-12 text-slate-600 mx-auto animate-pulse" />
          <h3 className="text-lg font-bold text-slate-300">No Graph Traversal Recommendations Found</h3>
          <p className="text-sm text-slate-500 max-w-md mx-auto">
            Try rating more movies or switching the algorithm mode above to expand graph connectivity.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {recommendations.map(({ movie, matchPercentage, rawScore, reasons, samplePath }) => (
            <div
              key={movie.id}
              className="group glass-card rounded-2xl overflow-hidden flex flex-col justify-between transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl hover:shadow-indigo-500/10 cursor-pointer"
              onClick={() => onSelectMovie(movie)}
            >
              <div>
                {/* Poster & Badges Header */}
                <div className="relative h-56 w-full overflow-hidden bg-slate-900">
                  <img
                    src={movie.poster}
                    alt={movie.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500 opacity-90 group-hover:opacity-100"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/20 to-transparent" />

                  {/* Match Percentage Badge */}
                  <div className="absolute top-3 right-3 bg-indigo-600/90 backdrop-blur-md text-white font-extrabold text-xs px-2.5 py-1 rounded-full border border-indigo-400/40 shadow-lg flex items-center space-x-1">
                    <Sparkles className="w-3.5 h-3.5 text-yellow-300" />
                    <span>{matchPercentage}% Match</span>
                  </div>

                  {/* Rating Badge */}
                  <div className="absolute bottom-3 left-3 flex items-center space-x-1 bg-slate-900/80 backdrop-blur-md px-2.5 py-1 rounded-lg text-amber-400 text-xs font-bold border border-slate-700">
                    <Star className="w-3.5 h-3.5 fill-amber-400" />
                    <span>{movie.rating}</span>
                  </div>
                </div>

                {/* Movie Details Content */}
                <div className="p-5 space-y-3">
                  <div className="flex items-baseline justify-between">
                    <h3 className="text-lg font-bold text-white group-hover:text-indigo-300 transition-colors">
                      {movie.title}
                    </h3>
                    <span className="text-xs text-slate-400 font-mono">{movie.year}</span>
                  </div>

                  <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">
                    {movie.overview}
                  </p>

                  {/* Explainable Graph Traversal Reasons */}
                  <div className="pt-2 border-t border-slate-800/80 space-y-1.5">
                    <span className="text-[10px] uppercase tracking-wider font-semibold text-slate-500 flex items-center space-x-1">
                      <GitCommit className="w-3 h-3 text-indigo-400" />
                      <span>Graph Reasoning Trail:</span>
                    </span>
                    <ul className="space-y-1">
                      {reasons.map((reason, idx) => (
                        <li key={idx} className="text-xs text-slate-300 flex items-start space-x-1.5">
                          <span className="text-indigo-400 font-bold">•</span>
                          <span className="leading-tight">{reason}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>

              {/* Card Footer Action: Trace Path in Visualizer */}
              <div className="p-4 bg-slate-900/60 border-t border-slate-800/80 flex items-center justify-between">
                <span className="text-xs text-slate-500 font-mono">
                  Graph Score: {rawScore}
                </span>

                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onHighlightPath(samplePath);
                  }}
                  className="flex items-center space-x-1 text-xs text-indigo-400 hover:text-indigo-300 font-medium hover:underline"
                >
                  <span>Trace Path</span>
                  <Play className="w-3 h-3" />
                </button>
              </div>

            </div>
          ))}
        </div>
      )}

    </div>
  );
}
